geometry_msgs/Vector3 master_linear
geometry_msgs/Vector3 master_angular
geometry_msgs/Vector3 pipe_linear
geometry_msgs/Vector3 pipe_angular

float32 ranges_scan
float32 confidence
float32 imu_yaw
float32 imu_pitch
float32 imu_roll
float32 depth
float32 pressure_inside
float32 batter_nuc
float32 battery_robot
float32 set_point_yaw
float32 set_point_pitch
float32 set_point_roll
float32 set_point_depth
float32 vo_x
float32 vo_y
float32 vo_z
float32 max_throtle

int16 upper_offset
int16 lower_offset
int16 thruster_h_fr
int16 thruster_h_fl
int16 thruster_h_br
int16 thruster_h_bl
int16 thruster_v_fr
int16 thruster_v_fl
int16 thruster_v_br
int16 thruster_v_bl

bool arm_hw
bool arm_sw
bool stabilize
bool depthhold
bool imu_reset

int8 lumen
int8 mov_mode
int8 opr_mode
int8 data_log
int8 count_vo_record


