obstacle_avoidance:
  pid_parameters:
    iou: 1.1
    kd_heading: 0.0
    kd_lateral: 0.0
    kd_range: 0.0
    ki_heading: 0.0
    ki_lateral: 0.0
    ki_range: 0.0
    kp_heading: -0.1901
    kp_lateral: -0.005
    kp_range: 0.0
    threshold: 1.1
    throtle: 0.3
pipeline_navigation:
  pid_parameters:
    iou: 1.1
    kd_heading: 0.00
    kd_lateral: 0.02
    kd_range: 0.05
    ki_heading: 0.0
    ki_lateral: 0.0
    ki_range: 0.0
    kp_heading: 0.001
    kp_lateral: 0.001
    kp_range: 0.0
    threshold: 1.1
    throtle: 0.3
serial_node:
  pid_parameters:
    kd_depth: 30.0
    kd_pitch: 20.0
    kd_roll: 30.0
    kd_yaw: 75.0
    ki_depth: 0.0
    ki_pitch: 0.0
    ki_roll: 0.0
    ki_yaw: 0.0
    kp_depth: 25.0
    kp_pitch: -25.0
    kp_roll: 12.0
    kp_yaw: 12.0
