obstacle_avoidance:
  pid_parameters:
    kd_heading: 0.0
    kd_lateral: 0.0
    kd_range: 0.0
    ki_heading: 0.0
    ki_lateral: 0.0
    ki_range: 0.0
    kp_heading: -0.1901
    kp_lateral: -0.001
    kp_range: 0.0
    throtle: 0.3
pipeline_navigation:
  pid_parameters:
    kd_heading: 0.0
    kd_lateral: 0.0
    kd_range: 0.0
    ki_heading: 0.0
    ki_lateral: 0.0
    ki_range: 0.0
    kp_heading: -0.001
    kp_lateral: -0.001
    kp_range: 0.0
    throtle: 0.3
serial_node:
  pid_parameters:
    kd_depth: 0.0
    kd_pitch: 0.0
    kd_roll: 0.0
    kd_yaw: 0.0
    ki_depth: 0.0
    ki_pitch: 0.0
    ki_roll: 0.0
    ki_yaw: 0.0
    kp_depth: 0.0
    kp_pitch: 0.0
    kp_roll: 0.0
    kp_yaw: 0.0
